name: CI
on:
  release:
    types: [published]
jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: test-id
      with:
        path: |
          ~/.d*
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
    - run: docker run -d -p 80:80 --rm --name my-app --health-cmd="curl --silent --fail 127.0.0.1:80 || exit 1" --health-start-period=1s --health-retries=1111 --health-interval=1s --health-timeout=5s nginx:1.20.1-alpine
    - run: sleep 5s
    - run: curl -v 0:80
    - run: docker commit --author "Maksim Kostormin" -m 'Create my-app based on nginx docker image.' my-app ${{ secrets.DOCKER_USERNAME }}/publish-images-to-dockerhub-with-github-actions
    - run: docker stop my-app
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: publish-id
      with:
        path: |
          ~/.d*
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
    # Login into Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Metadata
    - uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      name: Extract metadata (tags, labels) for Docker
      id: meta
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/publish-images-to-dockerhub-with-github-actions
    # Build and push docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
